version: '3.7'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: keycloak-admin/app
    volumes:
       - .:/var/www/html
    networks:
     - network
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
    networks:
      - network
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
    ports:
      - 8080:8080
    networks:
      - network
networks:
  network:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  mysqldatakeycloak:
    driver: "local"
  redisdata:
    driver: "local"
